name = "SafeSelfTriggered"
uuid = "0dfbb1cc-3cf0-4b16-94c4-4aaa3b5f0978"
authors = ["Arvind Adimoolam <asarvind.adimoolam@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.8.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
